### ISSUE TITLE
"The given key was not present in the dictionary" error

### ISSUE THREAD

**Issue by jjowens** [skrusty/AsterNET#1]
HI there,

I would like your help please. I've reported this issue at codeplex but I've realised I should have raised it here. Apologises.

I've created an IVR script on a webserver. It keeps failing randomly. To find out the issue, I wrote a CurrentDomain_UnhandledException. It prints out a message and the source of the error.

It gave this error.

```
The given key was not present in the dictionary. 

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at AsterNET.FastAGI.AGIConnectionHandler.Run() in e:\Projects\Codeplex\AsterNET\Asterisk.2013\Asterisk.NET\FastAGI\AGIConnectionHandler.cs:line 103
   at AsterNET.Util.ThreadTask.Run() in e:\Projects\Codeplex\AsterNET\Asterisk.2013\Asterisk.NET\Util\ThreadTask.cs:line 36
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

This is how I configured the agiServer component before starting it.
```
int PortNumber = ToolboxHelper.getSettingByNameAsInt("PortNumber");

            AsteriskFastAGI agiServer=new AsteriskFastAGI
            {
                MappingStrategy = new GeneralMappingStrategy(
                    new List<ScriptMapping>()
                    {
                        new ScriptMapping()
                        {
                            ScriptName = "callmonitor", // script name - passed by the Asterisk server
                            ScriptClass = "AsteriskAGI.CallMonitorAGI" // code to run for this script
                        }
                    })
            };

            agiServer.BindPort = PortNumber;

           try
            {
                agiServer.Start(); // Start the service. This runs synchronously - ctrl+c to exit
                
            }
            catch (Exception ex)
            {

            }
```

This error is occuring in the AsterNET code.

What's happening in AGIConnectionHandler.cs at line 103? What key is it expecting? This happens randomly, perhaps also when a call has connected with my script.

Am I missing something in my setup?

**Comment by jjowens** [comment]
I also had a look at the ThreadTask code on line 36.

```
public override void Run()
        {
            while (true)
            {
                AGIConnectionHandler job = ThreadPool.obtainJob(); // may have broken process here
                if (job == null)
                    break;
                job.Run();
            }
        }
```

I also looked at the code for AGIConnectionHandler.

```
internal AGIConnectionHandler obtainJob()
        {
            AGIConnectionHandler job = null;
            lock (jobs)
            {
                while (job == null && running)
                {
                    try
                    {
                        if (jobs.Count == 0)
                            Monitor.Wait(jobs);
                    }
                    catch (ThreadInterruptedException ex)
                    {
#if LOGGER
                        logger.Error("System.Threading.ThreadInterruptedException.", ex);
#else
                        throw ex;
#endif
                    }
                    if (jobs.Count > 0)
                    {
                        job = jobs[0];
                        jobs.RemoveAt(0);
                    }
                }
            }

            if (running)
                return job;
            else
                return null;
        }
```

Is it breaking because it cannot find one of the jobs by index? i.e. dictionary/list.

**Comment by skrusty** [comment]
When you say "webserver" do you mean you've written it in an asp.net project? If so, that wont work! You'll need to write it inside a console application or winforms.

**Comment by jjowens** [comment]
Hi skrusty,

It's written as a console application and it's installed on a server. It's a console applicaiton with framework set to 4.5.

This happens randomly.

**Comment by skrusty** [comment]
Trying to think what could cause this. The more information the better really. How often does this happen? Wondering how much logging we could turn on to catch some more information about this.

If you want to turn on tracing to try and output some more information, then i suggest you take a look at this post: https://asternet.codeplex.com/discussions/572963 and see if you can capture some  additional details to help narrow this down.

**Comment by jjowens** [comment]
I've downloaded the source and made some changes to find the root of the issue. Apologises for the long post.

In AGIConnectionHandler.cs, around lines 93, where it throws an exception. I commented out the "throw ex" and got it to write the error message.

```CSharp
catch (AGIException ex)
			{
#if LOGGER
				logger.Error("AGIException while handling request", ex);
#else
				//throw ex;
                              writeToLog("AGiConnectionError: AGIException:" + ex.ToString());
#endif
			}
```
I found where the error was occuring.

```
AGiConnectionError: Ex:System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AsterNET.FastAGI.AGIRequest.get_Script() in SNIP[..]\Asterisk.2013\Asterisk.NET\FastAGI\AGIRequest.cs:line 343
   at AsterNET.FastAGI.MappingStrategies.GeneralMappingStrategy.DetermineScript(AGIRequest request) in SNIP[..]Asterisk.2013\Asterisk.NET\FastAGI\MappingStrategies\GeneralMappingStrategy.cs:line 132
   at AsterNET.FastAGI.AGIConnectionHandler.Run() in SNIP[..]Asterisk.2013\Asterisk.NET\FastAGI\AGIConnectionHandler.cs:line 64
```
I looked inside AGIRequest.cs for line 343, GeneralMappingStrategy.cs for line 132 and AGIConnectionHandler.cs for line 64.

AGIRequest.cs 
```Csharp
#region Script()
		/// <summary>
		/// Returns the name of the script to execute.
		/// </summary>
		public string Script
		{
			get
			{
				if (script != null)
					return script;

				script = ((string)request["network_script"]); // <--- THIS IS LINE 343
				if (script != null)
				{
					Match scriptMatcher = Common.AGI_SCRIPT_PATTERN.Match(script);
					if (scriptMatcher.Success)
					{
						script = scriptMatcher.Groups[1].Value;
						parameters = scriptMatcher.Groups[2].Value;
					}
				}
				return script;
			}
		}
		#endregion
```

GeneralMappingStrategy.cs
```Csharp
        public AGIScript DetermineScript(AGIRequest request)
        {
            AGIScript script = null;
            if (mapAssemblies != null)
                lock (mapAssemblies)
                {
                    if (mapAssemblies.ContainsKey(request.Script))
                        script = mapAssemblies[request.Script].CreateInstance(); // THIS IS LINE 132
                }
            return script;
        }
```

AGIConnectioHandler.cs
```Csharp
AGIReader reader = new AGIReader(socket);
				AGIWriter writer = new AGIWriter(socket);
				AGIRequest request = reader.ReadRequest();
				AGIChannel channel = new AGIChannel(writer, reader, this._SC511_CAUSES_EXCEPTION, this._SCHANGUP_CAUSES_EXCEPTION);
				AGIScript script = mappingStrategy.DetermineScript(request); // THIS IS LINE 64
				Thread.SetData(AGIConnectionHandler.channel, channel);
```

So what happened, it was trying to find the script from the Dictionary (mapAssemblies) with the "network_script" variable/name so an instance of the script can be created and executed.

What is "network_script"? Is this something I need to declare in my AGIServer setup?

I looked at examples in https://asternetsamples.codeplex.com/ and I don't see anything, except I didn't use the Answer(); or HangUp(); in my script. Are they required? I was able to execute the script without those. The random hanging still occurs. Example

```Csharp
 public override void Service(AGIRequest param1, AGIChannel param2)
        {       
            Answer(); // Answer the call
// snip
            HangUp(); // Answer the call
        }
```

**Comment by skrusty** [comment]
network_script is a variable passed by Asterisk. It's part of the fastagi protocol, and it tells the fastagi server which script to run.

network_script will be matched with the script name you setup in the general mapping strategy, in your case: 

```ScriptName = "callmonitor"```

If this isn't being passed, then it's an issue with Asterisk. What version of Asterisk are you running?

If you go to the root console of asterisk, you can type

```agi set debug on```

this will output all the information sent to and from your fastagi server. You should see the network_script variable being passed.

**Comment by jjowens** [comment]
Hi Skrusty, that was the issue. There was no ScriptName provided.

The cause of the issue was down to the AGI_POOL_SIZE.and our Agi script. Our AGI script was hitting the Asternet AGI Server with multiple telephone calls and reached the maximum threading pools. This caused subsequent calls to provide a blank ScriptName. 

If you go to common.cs (https://github.com/skrusty/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Common.cs), on line 41.

``` Csharp
public const int AGI_POOL_SIZE = 10;
```
Increase to 100.

``` Csharp
public const int AGI_POOL_SIZE = 100;
```
It no longer errors.

Skrusty, thanks for your time and help. I appreciate it. You can close this issue down if you wish.

**Comment by 91Abdullah** [comment]
That means if you have an IVR App and an average inbound call load of lets say 200 calls at a time then you need to increase pool size to 200?

**Comment by skrusty** [comment]
You don't need to change the const, you simply need to call the correct constructor.

```c#
 public AsteriskFastAGI(IMappingStrategy mappingStrategy, string ipaddress, int port, int poolSize)
        {
            address = ipaddress;
            this.port = port;
            this.poolSize = poolSize;
            this.mappingStrategy = mappingStrategy;
        }
```

**Comment by skrusty** [comment]
91Abdullah: Each AGI Script holds on to it's own thread during the course of execution. So yes, the poolSize should represent your maximum concurrent load.

There has been talk from others about implementing some sort of Async functionality into AsterNET to allow thread re-use. Just talk so far though, all comments on the topic welcome mind you.
