### ISSUE TITLE
Asterisk 11.15: The application delimiter is now the comma, not the pipe

### ISSUE THREAD

**Issue by justinkillen** [skrusty/AsterNET#11]
Asterisk 11.15.0, running the originate command using multiple variables, I get the following error in asterisk:

"The application delimiter is now the comma, not the pipe.  Did you forget to convert your dialplan?"

I added the code: `AsterNET.Common.VAR_DELIMITER = new char[] {','};` to my startup which seems to resolve it, but ideally this would get set/updated as a function of the asterisk version.

**Comment by justinkillen** [comment]
Might want to also consider changing it away from a static variable, as if you were to create multiple instances pointing at different asterisk versions at least one of them would be broken at any given point.

**Comment by justinkillen** [comment]
Created pull request #12

**Comment by justinkillen** [comment]
http://forums.asterisk.org/viewtopic.php?f=1&t=88100&start=0 indicates that the change happened between 1.4 and 1.6

**Comment by skrusty** [comment]
fixed in #12 (416acc9)
