### ISSUE TITLE
AsterNet Hangup Event

### ISSUE THREAD

**Issue by muneeb249** [skrusty/AsterNET#13]
Dear skrusty,
    First of all hands off to the good work you have put on make this API.
I wanted to ask when a call ends what event is triggered,
because the problem is when Person a calls B, if call is not received then Hangup event is fired, but Person B picks up the call, and Person A ends the call Hangup event is not triggered.

Thanks in advance.

**Comment by skrusty** [comment]
hangup is only ever triggered (if i remember right) on a channel that's been answered. You might want to watch NewState events for a given channel.

**Comment by muneeb249** [comment]
Thanks for your input :)
