### ISSUE TITLE
How to check which Unhandled Event is triggerd

### ISSUE THREAD

**Issue by muneeb249** [skrusty/AsterNET#14]
Hi, I just wanted to know that 

 private void unhandled(object sender, ManagerEvent e)
        {
            Console.WriteLine("Unhandled Event");
            Console.WriteLine(e.Source);
        }

I have written the above piece of code and registered the event as 
manager.UnhandledEvent += new ManagerEventHandler(unhandled);

The unhandled event is fired correcty, what i wanted to know which event is fired causing Unhandled  Trigger to fire.

Thanks in Advance

**Comment by skrusty** [comment]
Off the top of my head I can't remember... Take a look at the attributes. I think there's one called Name or Event? Anyway, best place to look.

**Comment by muneeb249** [comment]
Thanks for the help :+1:

**Comment by skrusty** [comment]
Did you find what you needed? If so, maybe just reply with the specifics as others can use this if they need the same information.

**Comment by muneeb249** [comment]
No, I am still looking into it how to detect the unknown event

**Comment by skrusty** [comment]
I'll have a look today, i've done it before just been a long time!

**Comment by jonastelzio** [comment]
You can check it like this:
    if(e is NewStateevent) { //This is a newstateevent }

If you're getting a type called UnknownEvent then it's because Asterisk is fireing an eventtype that Asternet hasn't implemented. The attributes on UnknownEvent does not contain information about what type of event was fired. You NEED to implement the missing event.

**Comment by muneeb249** [comment]
Thanks a lot, that is what i was looking for :)
