### ISSUE TITLE
Different Unique Id for the same Event

### ISSUE THREAD

**Issue by muneeb249** [skrusty/AsterNET#17]
I have two machines, both listens for the same event i.e NewState Event. But both the machines have different unique ids, can you please verify it why it is happening.

**Comment by jonasswiatek** [comment]
Are you positive it's the exact same NewState event you're seeing?

Just to verify. One Asterisk server, with two different AsterNET Instances connecting to it?

**Comment by skrusty** [comment]
What do you mean by machines? Are you saying you're listening to AMI from two different Asterisk boxes or that you have to machines listening to AMI events from the same asterisk box?

**Comment by muneeb249** [comment]
I have two machines (computers) listening to the same asterisk server, and yes it is the new event which is fired on both the machines, but when i compare both the id's on the machines it is different,i can't understand why it so, really looking forward for your reply.
Thanks in advance

**Comment by skrusty** [comment]
I'd say this was more a question for #asterisk on freenode. I suggest however, you take a look at the raw data coming in from the tcp socket. You can turn on quite a lot of tracing for AsterNET, just follow this post. https://asternet.codeplex.com/discussions/572963

**Comment by muneeb249** [comment]
Thank for the help, it was asterisk's issue in Dial plan causing two different Unique Id's
