### ISSUE TITLE
How to originate a Call from agent to client

### ISSUE THREAD

**Issue by muneeb249** [skrusty/AsterNET#18]
Dear all, my requirement is when the user clicks on a button, a call i generated to the client.
How can I achieve this task from Originate Call.

I have a written a piece of code, but I am not sure it is the right way.

OriginateAction oc = new OriginateAction();            
            oc.Priority = "1";
            oc.Exten = "12345";
            oc.CallerId = "Rambo";
            oc.Context = "from-internal";
            oc.Channel = "SIP/20005427";
            oc.Timeout = 15000;
            oc.Async = true;
            ManagerResponse originateResponse = amiConn.SendAction(oc, oc.Timeout);

Thanks in advance, looking forward for your answer.

**Comment by skrusty** [comment]
Common Question.

Originate is a funny thing and often causes confusion. What you have to remember is the Channel that is called is called first, the extension or application that channel is connected to is done second.

So, if you wanted to call an outside line and connect it to an internal extension you would do:

```c#
OriginateAction oc = new OriginateAction();

oc.Priority = "1";
oc.Exten = "12345";  // extension to connect to
oc.CallerId = "Rambo";
oc.Context = "from-internal"; // in context
oc.Channel = "SIP/peer/20005427"; // this is the channel and dialled first!
oc.Timeout = 15000;
oc.Async = true;
ManagerResponse originateResponse = amiConn.SendAction(oc, oc.Timeout);
```

This would dial an outside line of 20005427 and connect that answered channel to extension 12345 in context from-internal.

**Comment by muneeb249** [comment]
Sir, Thanks a lot, that really helped my problem.
If one last thing i want to ask what is the role of 
oc.CallerId="Rambo";  in Originating the call

**Comment by skrusty** [comment]
When the channel is dialled (say outbound call) CallerId is the number and or name that's displayed to the callee. TO a SIP phone that could be a name and number, for an outbound call to a PSTN provider, it would be he number you want to be presented as.

**Comment by muneeb249** [comment]
thanks a lot :+1: Really Solved my problem.

**Comment by marquema** [comment]
this article really solved my problem too!!! thanks so much

**Comment by andrew-paes** [comment]
Hi,

Im trying this code and I'm not having success.

## Informations
### Scope
I want to make call from my SIP phone behind my Asterisk 13 PBX to an external line (external to my PBX) from code,

### Settings
I do have just one extension within the following settings:
* Caller ID: andrew-paes
* Extension: 8003
* Pass: 8003abc
* SIP Phone: 3CXPhone

### Scenario
If I dial from my SIP Phone to this external line number 3322-2233 everything is working fine, calling is being connected nice and easy. But When I try to run the below code, I can't make the same call, just nothing is happening. I tried to catch some event under Dial, DialBegin or DialEnd but without success. Just to clarify, I'm logging to my PBX and retrieving my Device and Extension status before try to make call.

```csharp
OriginateAction oc = new OriginateAction
{
	Priority = "1",
	Exten = "8003",
	CallerId = "Rambo",
	Context = "default", // in context
	Channel = "33222233",
	Timeout = 15000,
	Async = true
};

ManagerResponse originateResponse = manager.SendAction(oc, oc.Timeout);
```
### Issue
Now considering everything is working fine on PBX, what should be the correct code the achieve the scope?

**Comment by Deantwo** [comment]
> _wall-o-text_

Looks like you swapped `Exten` and `Channel`.

Might be easier if you read the Asterisk documentation on how AMI works.
Here: https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerAction_Originate

**Comment by andrew-paes** [comment]
> > Hi,
> > Im trying this code and I'm not having success.
> > ...
> 
> Looks like you swapped `Exten` and `Channel`.
> See what @skrusty showed earlier in the thread.
> Here: [#18 (comment)](https://github.com/AsterNET/AsterNET/issues/18#issuecomment-95481065)
> 
> Might be easier if you read the Asterisk documentation on how AMI works.
> Here: https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerAction_Originate

Prob when you were writing the answer I went to the old Java lib and read the correct specs for it.

This is the correct code for me:
```
OriginateAction oc = new OriginateAction
{
	Priority = "1", // priority of the call
	Exten = exten,  //where to call.. the target extension... internal extension or the outgoing number.. the 0[nomberToCall] 
	CallerId = "Rambo", // what will be showed on the phone screen (in most cases your phone)
	Context = "from-internal",
	Channel = String.Format("SIP/{0}", channel), the channel to be connected and this will ring before call the PSTN line
	Timeout = 20000, // the time that a pickup event will be waited for
	Async = true
};

ManagerResponse originateResponse = manager.SendAction(oc, oc.Timeout);
´´´

Tnx for your time.

**Comment by dddns** [comment]
Howdy,

I was testing this code and it's perfect, but i'd like to make it ring the internal extension first.
How could this be done, or possible?

Thanks in advanced,

**Comment by dddns** [comment]
Ah got it, works both ways, cooool!

**Comment by dddns** [comment]
One last thing to make this perfect.
When it call's the internal extension, i set the CallerId = "sometext", but on the phone i have another line with "unknown" that is the place where normally it's displayed the extension that is calling.
Would it be possible to set any info here? number or text.

Thanks in advanced,

**Comment by andrew-paes** [comment]
> One last thing to make this perfect.
> When it call's the internal extension, i set the CallerId = "sometext", but on the phone i have another line with "unknown" that is the place where normally it's displayed the extension that is calling.
> Would it be possible to set any info here? number or text.
> 
> Thanks in advanced,

Could you please give us more information?

Who is calling? Another extension, a PSTN phone?
Your AMI event is handling it and trying to foward to any other extension?
"on the phone i have..." What phone? A SIP Phone connected to your PBX?

Regards,

**Comment by dddns** [comment]
Andrew, my code below, and image on what appears on the phone screen.
You can see in the image below, when the extension rings it appears "mycallerID" that i defined, but below there a "unknown".
If I perform a normal call to the extension, I have the name and extension on the screen.
How would it be possible to set something for the line that appears "unknown"?

            ox.Priority = 1
            ox.Exten = "234500500"
            ox.CallerId = "mycallerID"
            ox.Context = "from-internal"
            ox.Channel = "SIP/20"
            ox.Timeout = 30000
            ox.Async = True

![image](https://user-images.githubusercontent.com/13902147/134730759-d56de403-689c-413c-b0aa-2117d59c9cd2.png)
![image](https://user-images.githubusercontent.com/13902147/134730778-458d1535-5f60-4594-83ab-b537c05a7b2f.png)

**Comment by Deantwo** [comment]
> How would it be possible to set something for the line that appears "unknown"?

Since it is the PBX calling your phone, it technically doesn't have a phone number, that is likely why it shows as "Unknown". I doubt there is a way to change that on the AMI side, if it is possible at all, but you could probably ask on the Asterisk forums if someone there knows more about it.

**Comment by dddns** [comment]
Oh got it, will stay this way then!
Thank you,
