### ISSUE TITLE
Best event for keeping a list of current calls

### ISSUE THREAD

**Issue by Suemo** [skrusty/AsterNET#19]
Hey,

I am trying to write an application that will keep a listing of any active call on the PBX and their current status.  Ideally i am looking for data points like:  Source, Destination, Inbound/outbound, call duration, etc...

is there an even or 2 that better lend themselves to keeping this in memory list?

**Comment by jonasswiatek** [comment]
I do this in my setup, for billing purposes. If you need to track it through SIP attended and blind transfers, local channels and all sorts of things it's a relatively large amount of state modelling.

You can start by listening for NewState events of the type Ring, Ringing and Up to see when channels are formed and bridged. You can detect when a call ends by listening for the Hangup event.

When running AsterNET in debugging mode, you can see a list of all events that gets fired from Asterisk in the output console in VS.NET.

**Comment by skrusty** [comment]
Yeah, NewState and NewChannel are going to be key to modelling call state to start with. The more complex you want to model that information, the more events you'll want to bring into your model.

https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+ManagerEvent_Newchannel
https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+ManagerEvent_Newstate

Hope that helps.

**Comment by Suemo** [comment]
Thanks for the info.  Those were the 2 events I was eyeing up.  Since a call seems to be made of 2+ channels, I was trying to come up with a way to merge both sides (channels) of a call into a single record for the end users.   I am going to attempt to use the Bridge event to merge the data from the 2 channels into a single object..  Thanks for the guidance!!!
