### ISSUE TITLE
Putting a cell phone number as exten. 

### ISSUE THREAD

**Issue by luknik001** [skrusty/AsterNET#2]
I'm trying to call a cell phone number after i pickup on an internal fixed phone, but it doesn't work, i just get a message from an operator that the number doesn't exit. But if i put a cellphone number as a channel it calls it regulary i don't know what is going on... This is the code that i was trying with, but it doesn'work. The fixed phone is called like it should, but the cell phone isn't...

    var host = "somehost";
    Int32 port = someport;
    var user = "someuser";
    var password = "somepassword";
    var manager = new ManagerConnection(host, port, user, password);
    manager.Login();

    var originateAction = new OriginateAction();
    var originateResponse = new ManagerResponse();

    originateAction.Channel = "SIP/1040";
    originateAction.CallerId = "1040";
    originateAction.Context = "from-pstn";
    originateAction.Exten = "SIP/CH_CABLECOM_BSL_OUT/somephonenumber";
    originateAction.Priority = "1";
    originateAction.Timeout = 30000;
    originateAction.Async = true;

    originateResponse = manager.SendAction(originateAction);

**Comment by skrusty** [comment]
Exten Property should be a dialplan extension, within the given context (Context Property).

It should not contain a channel.

Channel is always dialled first, and then, once answered, the extension is dialled.
