### ISSUE TITLE
OriginateAction blocks for reading other events

### ISSUE THREAD

**Issue by pajzo** [skrusty/AsterNET#21]
If i make .SendAction(obj) with a OriginateAction - the AsterNet stops handle events until i accept the call on my phone. I can see in the code its bescause of "WaitOne" its block the thread until a response is recived.

Can i do anything to prevent that? So i can read/handle events while the OriginateAction call is not answered.

**Comment by skrusty** [comment]
Are you using Async option in your Originate? That should ensure that you don't wait until the call is answered.

Eventing in ASterNET isn't great (inheritied from the previous code maintainer) but we're working to address it. If you have suggestions, you'll find a issue discussion on the matter here: https://github.com/skrusty/AsterNET/issues/15 (read down)

**Comment by pajzo** [comment]
@skrusty My bad! The async = true resolved my problem - i have not seen that property.

Thanks for a good libary and fast support! :-)
