### ISSUE TITLE
Feature Request, Add EarlyMedia setting to originate

### ISSUE THREAD

**Issue by mrlane** [skrusty/AsterNET#23]
Add EarlyMedia setting to OriginateAction

**Comment by skrusty** [comment]
Feel free to fork and add, it should be pretty simple. Just add the property to the Originate action and test. If you're happy it works, submit a pull request.

**Comment by mrlane** [comment]
I added the property to the originate action, it bombs out with an index out of range error, didn't get much further than that.

**Comment by skrusty** [comment]
Can you provide more information? Where is the error happening?

**Comment by skrusty** [comment]
closed due to inactivity
