### ISSUE TITLE
GetVarAction always timeout

### ISSUE THREAD

**Issue by SVD33** [skrusty/AsterNET#25]
hello. 

I want to get the value of the channel variable after event Dial. 

i set channel value 
[from-pstn-custom] 
exten => _X.,1,Set(__ORIGINAL_DID33=${EXTEN}) 
exten => _X.,n,goto(ext-did,${EXTEN},1) 

in code

    private void manager_Dial(object sender, DialEvent e)
    {
        string ordid = "";
        ordid = GetVar(e.Channel, "ORIGINAL_DID33");
        MessageBox.Show(ordid);
    }

    private string GetVar(string channel, string varname)
    {
        string result = "";
        try
        {
            Manager.Action.GetVarAction gv = new Manager.Action.GetVarAction(channel, varname);
            AsterNET.Manager.Response.ManagerResponse mr = manager.SendAction(gv);
            result = mr.Attributes[varname];
        }
        catch (Exception ex)
        { }
        return result;
    }
but, I always get Response TimeOut Exception 

in telnet 

Action: GetVar 
Channel: Local/033@from-queue-000001a3;2 
Variable: ORIGINAL_DID33 

returns the value of the variable ORIGINAL_DID33 

in Debug

Debug:[ManagerReader-47] ManagerConnection:DispatchResponse - Dispatch response packet : response: Error, actionid: 42109742_3#, message: Permission denied
   Info:[] ManagerConnection:login - Determined Asterisk version: ASTERISK_1_0
  Debug:[] ManagerConnection:DispatchEvent - Dispatching event: ConnectEvent {ProtocolIdentifier:Asterisk Call Manager/1.3; Reconnect:false; DateReceived:12:17:48}
   Info:[] ManagerConnection:DispatchEvent - Connected via Asterisk Call Manager/1.3
...
Debug:[ManagerReader-47] ManagerConnection:DispatchEvent - Dispatching event: DialEvent {DialString:033; SubEvent:Begin; Destination:SIP/033-00000acb; CallerIdName:3912266033; CallerIdNum:9069148833; DestUniqueId:1435209519.3671; DateReceived:12:18:40; Privilege:call,all; UniqueId:1435209519.3669; Channel:Local/033@from-queue-000001c5;2; Attributes:[connectedlinenum:3912266033; connectedlinename:<unknown>]}
  Debug:[ManagerReader-47] ManagerConnection:SendToAsterisk - Sent action : '42109742_7' : GetVarAction {Action:GetVar; Variable:ORIGINAL_DID33}
Первый этап обработки исключения типа "AsterNET.Manager.TimeoutException" в AsterNET.dll
Поток 0x5310 завершился с кодом 0 (0x0).
Поток 0x6bfc завершился с кодом 259 (0x103).
Поток 0x5748 завершился с кодом 259 (0x103).

**Comment by skrusty** [comment]
Are you using Async events? Calling a method from within an event can cause AsterNET to lock up, as the ConnectionManager thread is already locked processing your dial event!

See #21

**Comment by SVD33** [comment]
I used not asynchronous events. when replaced by asynchronous everything started to work fine.
thanks **skrusty**.
