### ISSUE TITLE
Hold Event for AsterNEt

### ISSUE THREAD

**Issue by muneeb249** [skrusty/AsterNET#27]
Deal All, 
              I just wanted to know, when call is on hold , hold event is fired by Asterisk, but your Api is not firing the Hold Event, can you please also differentiate between Hold and HoldedCall Event.

Thanks in Advance.

**Comment by skrusty** [comment]
I suspect the version of Asterisk! In Asterisk with AMI v2, some of the events and actions have changed. Check with official asterisk documentation in relation to the version of Asterisk you're connecting too.
