### ISSUE TITLE
Updated nuget

### ISSUE THREAD

**Issue by jonasswiatek** [skrusty/AsterNET#3]
Hey!

Thanks for the library - works great!

Is it possible that you could update the nuget. Right now I'm using your library as a submodule in my project to get the latest version that is compatible with asterisk 13 - however it would be great if I could use the nuget instead.

**Comment by skrusty** [comment]
Yeah sure. I've been meaning to do it for a while. I'll update this when it's done, should get chance some time today.

Version 1.0.1, here we come :)

**Comment by jonasswiatek** [comment]
Awesome! Thanks :D

**Comment by skrusty** [comment]
Nuget and GitHub released updated to 1.0.1. Enjoy!
