### ISSUE TITLE
RedirectAction not getting a response

### ISSUE THREAD

**Issue by erikgmiller** [skrusty/AsterNET#32]
Hi I've been stuck on this for a couple days now, when i do SendAction with a Redirect it does the transfer but i never get a response from SendAction and it throws a timeout exception.  Here is what i am doing:

1. I create a connection and dial a phone number with async OriginateAction.
2. When i answer the call i start playing an announcement and waiting for a DTMF key
3. When the key is pressed i handle the event and want to transfer at this point.
4. The transfer does work but SendAction never returns (I set the timeout to 60 seconds).  Even when i hang up the call it still just waits for the timeout to happen.

I'm using a Freepbx dialplan. 
Any thoughts would be appreciated.

Thanks
Erik

**Comment by skrusty** [comment]
Hi, the problem is you are creating an response based action INSIDE an event raised by ConnectionManager. This causes a blocking problem with the event handler.

You need to either not raise the SendAction inside an event or use UseAsync=true.

Hope that helps,
Ben

**Comment by erikgmiller** [comment]
Ahhhh, that makes sense.  Works perfect now.

Thanks
Erik
