### ISSUE TITLE
Virtual test environment for virtual IP PBX

### ISSUE THREAD

**Issue by pradeepWritso** [skrusty/AsterNET#34]
Hi All, 

Hope you are doing great. 

I am new for PBX integration so sorry in advance if I ask basic/stupid question. 
I am going to develop a [predictive dialer](https://en.wikipedia.org/wiki/Predictive_dialer) for [yeastar MyPbx U520](http://www.yeastar.com/Products/MyPBX-U5-Series) that will handle around 30 Agents using AsterNET but my problem is that I don't have IP PBX Server hardware in development environment, So Is there any virtual PBX server / Test Environment where I can test my application.

Thank in advance for your support

**Comment by skrusty** [comment]
AsterNET only works with Asterisk. Is your PBX based on Asterisk? If not, AsterNET will be of little use to you.

**Comment by pradeepWritso** [comment]
Hi Ben,

Thanks for reply, 
Is your PBX based on Asterisk - Yes [Yeastar MyBBX U520 support Asterisk Management Interface (AMI)](http://www.yeastar.com/Solutions/Integration_of_MyPBX_with_CRM).

Can you please suggest me - How I can test my Predictive Dialer without having real PBX hardware.

Thanks again.

**Comment by skrusty** [comment]
Download a copy of Asterisk? Maybe find a pre-built virtual machine image?

Google "asterisk virtual machine image"
