### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by JobaDiniz** [skrusty/AsterNET#35]
Almost one year since the last commit, is this project dead?

**Comment by skrusty** [comment]
no?

**Comment by JobaDiniz** [comment]
I've downloaded the nuget package and when debugging my code (using this lib) VS says *ManagerReader.cs not found*

**Comment by skrusty** [comment]
Because you've downloaded the pre-compiled library and not the source code. If you want to step into ASterNET you'll need to download the source code.

**Comment by JobaDiniz** [comment]
It's not that, I'm not stepping into a method... I think the *.pdb* files that you added to nuget package is wrong. If I delete the AsterNET.pdb file, this "error" does not occur.

Besides that, I'm trying to send a command action and it throws a timeout exception, which it shouldn't. Something is strange, because I was using another lib and timeout errors didn't happen.

**Comment by skrusty** [comment]
Can you explain what you're doing? Are you calling SendAction from inside a manager event? If so, you'll get a timeout exception, because MangerConnection is blocked by the currently raised event.

You can change this behaviour by using UseAsync.

If this still doesn't help, please provide more information or snippet of your code.
Thanks

**Comment by JobaDiniz** [comment]
> Are you calling SendAction from inside a manager event
**YES**

What do you mean by *UseAsync* ? Can you provide an example?

**Comment by skrusty** [comment]
It's a common issue, and been asked about many times in other (now closed) issues.

https://github.com/skrusty/AsterNET/issues/32

This property exists on the ManagerConnection.

**Comment by JobaDiniz** [comment]
There is not *UseAsync* in the action class.
*OriginateAction* is the only one I found which has *Async* property.

**Comment by skrusty** [comment]
> This property exists on the ManagerConnection.

**Comment by JobaDiniz** [comment]
`UseASyncEvents` which is a public field of `ManagerConnection`.

Thanks.
