### ISSUE TITLE
FastAGI not working

### ISSUE THREAD

**Issue by JobaDiniz** [skrusty/AsterNET#37]
I was using https://github.com/roblthegreat/Asterisk.NET library.. old right? However, AGI is working there and somehow I couldn't get to work with *this library*.

I've set up just like [your example](https://github.com/skrusty/AsterNET/blob/master/Asterisk.2013/Asterisk.NET.Test/Asterisk.NET.Test/Program.cs#L51-L69) and asterisk is printing out:

```
 == Using SIP RTP CoS mark 5
    -- Executing [12345678@sf-internal:1] NoOp("SIP/7004-00000054", "AQUI") in new stack
    -- Executing [12345678@sf-internal:2] AGI("SIP/7004-00000054", "agi://IP/SimpleIvr") in new stack
 agi://IP/SimpleIvr: No script configured for URL 'agi://IP/SimpleIvr' (script 'SimpleIvr')
    -- <SIP/7004-00000054>AGI Script agi://IP/SimpleIvr completed, returning 0
    -- Executing [12345678@sf-internal:3] Hangup("SIP/7004-00000054", "") in new stack
  == Spawn extension (sf-internal, 12345678, 3) exited non-zero on 'SIP/7004-00000054'
  == Manager 'secfut' logged off from IP
    -- Registered SIP '7002' at IP:5060
cubietruck*CLI>
```

**Comment by skrusty** [comment]
Have you replaced the IP of your FastAGI server with the work 'IP' in the output? If not, you've not configured the dialplan correctly!

**Comment by JobaDiniz** [comment]
I've figured it out... My scripts classes were in a different assembly, so I had to set the Assembly in ScriptMapping.

BTW, I've also created another mapping strategy, which I called `DependencyResolverMappingStrategy`.
Nowadays it is common to use dependency injection, so this new strategy uses whatever *IoC* you're using (SimpleInjector, Unity, etc) to instanciate the AGIScritps.

**Comment by skrusty** [comment]
Feel free to fork and and send over a pull request!

Thanks, Ben

**Comment by fdervishi90** [comment]
@JobaDiniz is `DependencyResolverMappingStrategy` implemented?

**Comment by Deantwo** [comment]
> @JobaDiniz is `DependencyResolverMappingStrategy` implemented?

I don't know what that has to do with this issue, you might want to make a new issue if you have a bug or question.
