### ISSUE TITLE
UnhandledEvent in VB.NET WinForm

### ISSUE THREAD

**Issue by Ghini76** [skrusty/AsterNET#4]
Hi Skrusty and congratulations for the work!
I'm running tests with VS2013 and VB.NET Framework 4.0, but I have a problem with the lines:

private ManagerConnection manager = null;
manager = new ManagerConnection (address, port, user, password);
manager.UnhandledEvent + = new ManagerEventHandler (manager_Events);

in VB.NET I translated thus:

     Private Sub Chiama2 ()
         Dim Manag As AsterNET.Manager.ManagerConnection = New AsterNET.Manager.ManagerConnection (My.Settings.Asterisk_host, My.Settings.Asterisk_port, My.Settings.Asterisk_usr, My.Settings.Asterisk_psw)
         Manag.UnhandledEvent = New Manager.ManagerEventHandler (AddressOf Event)
     end Sub

     Private Sub Event ()
          'event handling code
     end Sub

 The problem is that "Manag.UnhandledEvent" is not a valid property ...
 can you tell me why or how to fix it?

 thanks a lot

Ghini

**Comment by skrusty** [comment]
Are you using Source, Release or Nuget and can you confirm the version you're running please?

I'm not very up on VB.NET, but the events that exist on the ManagerConnection class will exist for both VB.NET and C#.

https://github.com/skrusty/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L166

I ran an example through a c# to vb.net converter and got this. Maybe this will help?

C#
```c#
var manager = new ManagerConnection(address, port, user, password);
manager.UnhandledEvent += new ManagerEventHandler(manager_Events);
```

VB.NET
```vb.net
Dim manager = New ManagerConnection(address, port, user, password)
manager.UnhandledEvent += New ManagerEventHandler(manager_Events)
```

**Comment by Ghini76** [comment]
Hi Ben,

thanks for yopur reply.

 

I’m using Version 1.0.1 downloaded by NuGet.

 



 

In the dropdown missing property UnhandledEvent to assign the event handler…. L

 

Thanks


Fabrizio

 

 

 

Da: Ben Merrills [mailto:notifications@github.com] 
Inviato: mercoledì 4 marzo 2015 11:53
A: skrusty/AsterNET
Cc: Ghini76
Oggetto: Re: [AsterNET] UnhandledEvent in VB.NET WinForm (#4)

 

Are you using Source, Release or Nuget and can you confirm the version you're running please?

I'm not very up on VB.NET, but the events that exist on the ManagerConnection class will exist for both VB.NET and C#.

https://github.com/skrusty/AsterNET/blob/master/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L166

I ran an example through a c# to vb.net converter and got this. Maybe this will help?

C#

var manager = new ManagerConnection(address, port, user, password);
manager.UnhandledEvent += new ManagerEventHandler(manager_Events);

VB.NET

Dim manager = New ManagerConnection(address, port, user, password)
manager.UnhandledEvent += New ManagerEventHandler(manager_Events)

**Comment by skrusty** [comment]
Have you tried doing this as per my example above?

**Comment by Ghini76** [comment]
Yes, but as I said "UnhandledEvent" is not present in the autocompletelist of methods / properties...
I tried it in C# and everything works ...

**Comment by ddegg** [comment]
Hi Ben,

I am having same problem with missing "UnhandledEvent".

any ideas would be appreciated


Thanks,

DD

**Comment by skrusty** [comment]
I will fire up vs later and have a play with VB.NET. any suggestions welcome as the code for this and all other events is the same!

**Comment by garysprice** [comment]
there are 2 ways of handling asternet events vb.net. that I know of and use - there maybe more but...

1.
'probably put into your form.load
'you will have to add handlers for all event manually though. I prefer 2nd option...
Dim Manag As New AsterNET.Manager.ManagerConnection("xxx", xxx, "xxx", "xxx")
AddHandler Manag.UnhandledEvent, AddressOf evManagerUnhandled

    Private Sub evManagerUnhandled()
'your code goes here
    End Sub

2.
'declare the manager as private/public with events
Private WithEvents Manager As New AsterNET.Manager.ManagerConnection("xxx", xxx, "xxx", "xxx")

    Private Sub evManagerUnhandledEvent(sender As Object, e As AsterNET.Manager.Event.ManagerEvent) Handles Manager.UnhandledEvent
'your code goes here
    End Sub

**Comment by dgrah** [comment]
Here is what I have done in the past


    Private Delegate Sub delUnhandled(e As Asterisk.NET.Manager.Event.ManagerEvent)

    Private Sub Form1_Load(sender As Object, e As System.EventArgs) Handles Me.Load
         mancon= New ManagerConnection("xxx", xxx, "xxx", "xxx")
         AddHandler astCon.UnhandledEvent, AddressOf managerUnhandledEvent
    End Sub


    Private Sub managerUnhandledEvent(sender As Object, e As Asterisk.NET.Manager.Event.ManagerEvent)
        If InvokeRequired Then
            Me.BeginInvoke(New delUnhandled(AddressOf unhandledEvent), New Object() {e})
        Else
            unhandledEvent(e)
        End If
    End Sub
  

    Private Sub unhandledEvent(e As Asterisk.NET.Manager.Event.ManagerEvent)
        'do stuff
    End Sub

`

**Comment by ddegg** [comment]
Hi Guys,

Thanks for your input, much appreciated

as previously suggested, I am now using the following, whic exposes all the
events:
 Private WithEvents mgr As New ManagerConnection("192.168.0.198", 5038,
"admin", "amp111")

and then:
Private Sub mgrQueue(ByVal sender As Object, ByVal e As NewStateEvent)
Handles mgr.NewState

        txtMsg.Text += "*** " + e.CallerId + " * " + e.CallerIdNum + " ***"

 End Sub

unfortunately, it gets fired multiple times, only the first firing has true
caller info

would using your suggested code fix this?


once again, appreciated.


DD



ᐧ

**Comment by skrusty** [comment]
You'll get a NewState event each time a channel enters a new state! Depending on the state, depends on what information is returned as part of it.

Are all the events for the same channel? 

Not sure technically this is an issue. AMI is about state modelling, you can't assume an event is atomic in it's own right but part of a sequence of events describing the state of a channel, for example.

**Comment by dgrah** [comment]
Check e.Channel, e.ChannelState and e.ChannelStateDesc to see what the New State is about.
