### ISSUE TITLE
AsterNet uthentication issue

### ISSUE THREAD

**Issue by k07** [skrusty/AsterNET#40]
I  am new in Asterisks .i create a user in my freePBX server.I getting Authentication error when connecting to server from Aster-net sample application.Please help me to solve this

**Comment by skrusty** [comment]
Can you give more information please, like what the error is? Any trace output from the debug/output window in visual studio etc?

**Comment by k07** [comment]
freePBX server info : host: 192.168.1.155 , user : admin ,pw :1234: 
Error msg : 'error connecting to 192.168..155 Error:Timeout waiting for protocol Identifier'.
I getting this error in Astray

**Comment by k07** [comment]
this is connecting code section 
' AstCon = new ManagerConnection(ConfigurationManager.AppSettings["astHost"],
                    int.Parse(ConfigurationManager.AppSettings["astPort"]),
                    ConfigurationManager.AppSettings["astUser"], ConfigurationManager.AppSettings["astPass"]);

                AstCon.NewState += astCon_NewState;
                AstCon.Link += astCon_Link; // added to support AMI 1.0 (Asterisk 1.4)
                AstCon.ConnectionState += astCon_ConnectionState;
                AstCon.Login();
'

**Comment by skrusty** [comment]
And you've populated the AppSettings values in app.config I assume correctly?

What version of Asterisk are you running?

**Comment by k07** [comment]
Asterisk 12

**Comment by k07** [comment]
appConfig values:
 <appSettings>
    
    <add key="astHost" value="192.168.1.10"/>
    
    <add key="astPort" value="8088"/>
    
    <add key="astuser" value="admin"/>
    <add key="astPass" value="123"/>

    
    <add key="astExten" value="101"/>
    
    <add key="astPeerType" value="SIP"/>
    
    <add key="astPeerID" value="101@192.168.1.10"/>
    
    <add key="astExtenContext" value="101"/>

**Comment by k07** [comment]
Please help me to solve this..

**Comment by skrusty** [comment]
Can you see a successful login from the Asterisk console for managed connection?

**Comment by k07** [comment]
no

**Comment by k07** [comment]
Authentication Failed Exception

**Comment by k07** [comment]
Now it's OK.Thank you for your support

**Comment by kashifiqb** [comment]
@k07,
>>Now it's OK.Thank you for your support
How did you solve this? I am also facing same issue on machine with static ip. On my VM with dynamic ip, it works fine.
