### ISSUE TITLE
How to impliment call Answering /Cancel Functionality ?

### ISSUE THREAD

**Issue by k07** [skrusty/AsterNET#42]
I am new in Asterisk.I just Implemented the calling functionality . Can you give me an idea for pick up call ,cancel call..

**Comment by k07** [comment]
format of AMI commands for answering call  ?

**Comment by skrusty** [comment]
This is more specific to AsterNET/AMI. I suggest you see the reply to your issue there.

**Comment by skrusty** [comment]
Duplicate issue #43
