### ISSUE TITLE
How to answer a call ?

### ISSUE THREAD

**Issue by k07** [skrusty/AsterNET#43]
Which AMI command is used to answer a call ? Which event is used to implement this functionality ..

**Comment by jonastelzio** [comment]
Orchastrating calls through AMI is much more complicated than it is through Fast AGI, ARI or just straight up Dial Plans. Is there any reason why you feel you need AMI?

**Comment by jonastelzio** [comment]
Orchastrating calls through AMI is much more complicated than it is through Fast AGI, ARI or just straight up Dial Plans. Is there any reason why you feel you need AMI?

**Comment by k07** [comment]
Then can you please give my an idea to  answer the call using Fast AGI or ARI

**Comment by jonastelzio** [comment]
Do you know how get an incoming call to enter an asterisk context and extension in your dial plan?

**Comment by skrusty** [comment]
k07: Do you mean answer it at the handset/phone? If so, that's not easy and is very dependant on the model of phone etc. 

If you simple mean "Answer the channel" then that's easier, but we need to know why you want to do it to help further.

**Comment by k07** [comment]
This is my code section to make call
AsterNET.Manager.Action.OriginateAction oc = new AsterNET.Manager.Action.OriginateAction();
            oc.Context = "default";
            oc.Priority = "1";
            oc.Channel = "SIP/105";
            oc.CallerId = "104";
            oc.Exten = "105";
            oc.Timeout = 30000;
            oc.Async = true;
            AsterNET.Manager.Response.ManagerResponse response = manager.SendAction(oc);

**Comment by k07** [comment]
How to receive this call  and answer  from Exten:105

**Comment by skrusty** [comment]
Right....

Not so easy. What you're asking is "How do i get the phone on extension 105 to auto answer an incoming call". Correct?

**Comment by k07** [comment]
Not auto answer. I Just want to display a message "1004 calling..." and i want to  pick uo that call .

**Comment by skrusty** [comment]
"pickup" ? as in answer it? without someone pressing the answer button or lifting the handset?

This is why we say you need to be specific. Sorry, we don't mean to be pedantic, but it's a complex topic made more complicated by lack of understanding.

**Comment by k07** [comment]
ok sorry...

**Comment by k07** [comment]
I mean "pressing the answer button"

**Comment by skrusty** [comment]
Right, nothing to do with Asterisk or AsterNET. This it very specific to your phone.

What phone are you using? Often they require a custom header to be sent in the SIP INVITE message that tells the phone to auto-answer.

**Comment by k07** [comment]
We are using  linphone

**Comment by skrusty** [comment]
http://lmgtfy.com/?q=linphone+auto+answer

**Comment by k07** [comment]
ok thanks  for your support.
