### ISSUE TITLE
AMI’s AgentConnect event rarely being fired

### ISSUE THREAD

**Issue by ben-guri** [skrusty/AsterNET#44]
Hi. I'm developing a .NET application that utilizes AsterNet to register to AMI's events like NewChannel event, AgentConnect event and HangUp event. Our company's asterisk guy has set up a dev asterisk server (version 13) , a call queue, and two extensions associated with that queue. When i debug the application, and call the queue, i get the NewChannel event always fired, but when i pick up one of the two extension's phones i dont always get the AgentConnect event fired, actually most of the times i don't. The HangUp even is also always fired.  my  AsterNet version is version 1.0.0. Thanks in advance.

**Comment by skrusty** [comment]
Hi.

1. Do you have "eventmemberstatus=yes" in queues.conf? (see http://www.voip-info.org/wiki/view/Asterisk+config+queues.conf)
2. Asterisk AMI really doesn't miss events, and as a result, AsterNET shouldn't (not saying it's impossible, but very unlikely) 

I suggest you have a look at the debug output window in Visual Studio to see what events are being emitted from AsterNET/Asterisk if you think something isn't being raised correctly.

**Comment by skrusty** [comment]
Also, are you running the latest version of AsterNET? From source or nuget?

**Comment by ben-guri** [comment]
from Asterisk 12 The configuration options eventwhencalled and eventmemberstatus have been removed. As a result, the AMI events QueueMemberStatus, AgentCalled, AgentConnect, AgentComplete, AgentDump, and AgentRingNoAnswer will always be sent. The Variable fields will also no longer exist on the Agent* events. These events can be filtered out from a connected AMI client using the eventfilter setting in manager.conf. []( https://wiki.asterisk.org/wiki/display/AST/New+in+12)

yes im running the latest AsterNet from nuget (1.0.0), i, gonna see now what comes up in the debug output.
thank you.

**Comment by ben-guri** [comment]
it appears that configuration seems to fix the issue, although it was deprecated since version 12. but it still puzzles me because before the event still fired, but only occasionally. i will test it again later without this configuration to be sure.

thanks @skrusty .
