### ISSUE TITLE
Answer in fastAGI 

### ISSUE THREAD

**Issue by k07** [skrusty/AsterNET#45]
i am new in asterNet .Can you a give me a brief description to Answer() in fastAgi. How can use this to answer a call

**Comment by skrusty** [comment]
Define 'Answer' a call?

Answer in terms of FastAGI means answer the channel so you can play audio over the channel (for example). It **doesn't ** mean Answer at a handset.

**Comment by k07** [comment]
Suppose  a channel SIp/100 is calling extn 101.Which event is fired in 101 or how to Answer to that call

**Comment by skrusty** [comment]
You can't do that with FastAGI. We've already explained that the Answer feature doesn't answer the call ringing at an extension, it answers a channel in asterisk. As explained in #43

**Comment by k07** [comment]
Thanks for replay, but didn't get any Solutions

**Comment by jonastelzio** [comment]
k07,

The Answer call in Fast AGI does exactly the same thing as the Answer-dialplan application does. Actually Fast AGI basically just execute dial plan applications, but from another server, with asterisk connected via TCP to obtain instructions on which dial plan apps to execute.

You can find the comprehensive list, and documentation, of all dial plan apps supported by asterisk here: https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Dialplan+Applications

**Comment by k07** [comment]
Then How can we communicate with other channel.I mean  answer that call. I am new to Aster.net So please forgive me if i made a silly mistake,

**Comment by skrusty** [comment]
Your questions are not AsterNET related, but Asterisk. You're understanding of Asterisk isn't supported here, please ask these questions here: https://community.asterisk.org/
