### ISSUE TITLE
Send  AGIAction to FastAGI and get a response

### ISSUE THREAD

**Issue by k07** [skrusty/AsterNET#46]
I create a AGIAction and how to send this to FastAGI ?

eg: **AgiAction agi = new AgiAction("SIP/1004", "MusicOnHold"); **

**Comment by jonastelzio** [comment]
Please post your extensions.conf file so we can see what you're trying to do. You need to send the channel to async agi using the AGI Dial Plan application to even be able to operate on it like that.
