### ISSUE TITLE
Which event is fired after call Orginate ?

### ISSUE THREAD

**Issue by k07** [skrusty/AsterNET#47]
this is my code 
---
                        OriginateAction oc = new OriginateAction();
			oc.Context = ORIGINATE_CONTEXT;
			oc.Priority = "1";
                        oc.Async = true;			
                         .......etc                 
			ManagerResponse originateResponse = manager.SendAction(oc, oc.Timeout);
 " call from  100 > 101 "
**NewState** event  is fired in receiving side 
 after  orginate call
 private void astCon_NewState(object sender, NewStateEvent e)
        {
        }
.Is it right event ? Then How to implement answer,hold... from receiving side

**Comment by jonastelzio** [comment]
This is an Asterisk specific question, and has nothing to do with AsterNET. Please refer to an Asterisk forum or something for help with actually getting Asterisk to work.

**Comment by k07** [comment]
Above code is from AsterNet test application.

**Comment by skrusty** [comment]
OriginateResponse event is fired.

**Comment by k07** [comment]
" OriginateResponse " is fired after answering channel
