### ISSUE TITLE
HangupAction() Not working.

### ISSUE THREAD

**Issue by pradeepWritso** [skrusty/AsterNET#49]
Hi,
I am new to Asterisk AMI, Aster.net api. So please forgive me if i made a silly mistake,
I'm developing an application in C# by using open source AsterNET to originate calls and its works fine,
My problem is I am not able to hangup call using Aster.net.
I am using following code to hangup a call:

HangupAction ha = new HangupAction(monitorChannel);
ManagerResponse hangupeResponse = manager.SendAction(ha);

Here I get monitorChannel from Monitoring_NewState() I my case it is SIP/120-00001ba2.

Code that i use to make a call:

OriginateAction oc = new OriginateAction();
oc.Context = ORIGINATE_CONTEXT;
oc.Priority = "1";
oc.Channel = SIP/120;
oc.CallerId = SomeMobileNO;
oc.Exten = SomeMobileNO;
oc.Timeout = ORIGINATE_TIMEOUT;
oc.Async = true;
ManagerResponse originateResponse = manager.SendAction(oc, oc.Timeout);

Please help me what I am doing wrong, 
Thanks in advance,

**Comment by skrusty** [comment]
Hi, can you tell me what exactly isn't working? 

What is the response from AMI? Is there any output in the Asterisk console? is there any output in the debug window of visual studio? The more information the better.

Cheers, Ben

**Comment by pradeepWritso** [comment]
Hi Ben,

Thanks for your reply.
My problem is solved now.
Now I am sending HangupAction() for both channel ('SIP/120-00001ba2', 'DAHDI/10-1').
I got these both channel in Monitoring_NewState();
Thanks again for your reply.
