### ISSUE TITLE
Call monitoring help

### ISSUE THREAD

**Issue by k07** [skrusty/AsterNET#52]
I am trying to  listing of any active call on the Asterisk and their current status. Can I get all  active channels from new state event ?? how to monitor all active channels from  monitorAction class??I am new in Asterisk please help me.

**Comment by skrusty** [comment]
Please see

https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+AMI+Events
http://forums.asterisk.org/

or #asterisk on irc.freenode.net

**Comment by k07** [comment]
This is my action 
CoreShowChannels

Action: CoreShowChannels
ActionID: 100

Code Section
AsterNET.Manager.Action.CoreShowChannelsAction coreSC = new Manager.Action.CoreShowChannelsAction();
            coreSC.ActionId = "100";
            AsterNET.Manager.Response.ManagerResponse response = manager.SendAction(coreSC);

**
I didn't get any Response**
