### ISSUE TITLE
Dialplan Config help 

### ISSUE THREAD

**Issue by k07** [skrusty/AsterNET#57]
**Proper channels aren't created when i calling from 5004 to  5005**  .Below  my dialplan part..Is it Correct  ?

[ Context 'from-internal' created by 'pbx_config' ]
  '5004' =>         1. Dial(SIP/5005,20)                          [pbx_config]
  '5005' =>         1. Dial(SIP/5004,20)                          [pbx_config]
  '5006' =>         1. Dial(SIP/5007)                             [pbx_config]
  '5007' =>         1. Answer()                                   [pbx_config]
                    2. Playback(hello-world)                      [pbx_config]
                    3. Hangup()                                   [pbx_config]
  Include =>        'from-internal-noxfer'                        [pbx_config]
  Include =>        'from-internal-xfer'                          [pbx_config]
  Include =>        'bad-number'                                  [pbx_config]

**Comment by skrusty** [comment]
Asterisk questions should be asked in the Asterisk Community. This is not the place to be asking about dialplan configurations!

**Comment by k07** [comment]
ok ..sorry for the inconvienence
