### ISSUE TITLE
Bridge Event problem (Asterisk 12)

### ISSUE THREAD

**Issue by xiron3** [skrusty/AsterNET#58]
Hi,

I have a problem with ManagerConnection.Bridge Event. The problem is that Bridge event never fires.
I have Asterisk 12 and AsterNET from NuGet. 
I also tried to use the link and unlink events but they also do not work (not fires at all).

This is piece of my code. 

public bool ConnectAsterNet()
        {
            // Create ManagerConnection
            AsterManager = new ManagerConnection(_ServerAdress, _ServerPort, UserName, Password);

            //AddEvents
            AsterManager.UnhandledEvent += AsterManager_UnhandledEvent1;
            AsterManager.OriginateResponse += AsterManager_OriginateResponse;

            AsterManager.Dial += AsterManager_Dial;
            AsterManager.Hangup += AsterManager_Hangup;
            AsterManager.Transfer += AsterManager_Transfer;
            AsterManager.ExtensionStatus += AsterManager_ExtensionStatus;
            AsterManager.ConnectionState += AsterManager_ConnectionState;
            AsterManager.NewState += AsterManager_NewState;
            AsterManager.UseASyncEvents = true;
            AsterManager.Bridge += AsterManager_Bridge;
  	    AsterManager.Login();
}

     private void AsterManager_Bridge(object sender, AsterNET.Manager.Event.BridgeEvent e)
     {
            Console.WriteLine("Bridge:" + e.ToString());
     }

Below you can find the logs regarding bridge directly from my AMI

Event: BridgeCreate
Privilege: call,all
BridgeUniqueid: 315ec63d-fabc-4dd3-a46d-ecd48b85c144
BridgeType: basic
BridgeTechnology: simple_bridge
BridgeCreator: <unknown>
BridgeName: <unknown>
BridgeNumChannels: 0

Event: BridgeEnter
Privilege: call,all
BridgeUniqueid: 315ec63d-fabc-4dd3-a46d-ecd48b85c144
BridgeType: basic
BridgeTechnology: simple_bridge
BridgeCreator: <unknown>
BridgeName: <unknown>
BridgeNumChannels: 1
Channel: SIP/7002-00000000
ChannelState: 6
ChannelStateDesc: Up
CallerIDNum: 7002
CallerIDName: 7002
ConnectedLineNum: 7003
ConnectedLineName: <unknown>
AccountCode: 
Context: from-internal
Exten: 
Priority: 1
Uniqueid: 1459363700.2

Event: BridgeEnter
Privilege: call,all
BridgeUniqueid: 315ec63d-fabc-4dd3-a46d-ecd48b85c144
BridgeType: basic
BridgeTechnology: simple_bridge
BridgeCreator: <unknown>
BridgeName: <unknown>
BridgeNumChannels: 2
Channel: Local/7003@from-internal-00000000;1
ChannelState: 6
ChannelStateDesc: Up
CallerIDNum: 7003
CallerIDName: <unknown>
ConnectedLineNum: 7002
ConnectedLineName: 7002
AccountCode: 
Context: macro-dial-one
Exten: s
Priority: 47
Uniqueid: 1459363700.0

Event: BridgeLeave
Privilege: call,all
BridgeUniqueid: 315ec63d-fabc-4dd3-a46d-ecd48b85c144
BridgeType: basic
BridgeTechnology: simple_bridge
BridgeCreator: <unknown>
BridgeName: <unknown>
BridgeNumChannels: 1
Channel: SIP/7002-00000000
ChannelState: 6
ChannelStateDesc: Up
CallerIDNum: 7002
CallerIDName: 7002
ConnectedLineNum: 7003
ConnectedLineName: <unknown>
AccountCode: 
Context: from-internal
Exten: 
Priority: 1
Uniqueid: 1459363700.2

Event: BridgeDestroy
Privilege: call,all
BridgeUniqueid: 315ec63d-fabc-4dd3-a46d-ecd48b85c144
BridgeType: basic
BridgeTechnology: simple_bridge
BridgeCreator: <unknown>
BridgeName: <unknown>
BridgeNumChannels: 0

**Comment by jonastelzio** [comment]
The Bridge-event is a legacy event no longer used by Asterisk 12. You can also see that the event actually isn't fired.

https://wiki.asterisk.org/wiki/display/AST/Asterisk+12+AMI+Events

@skrusty or is the Bridge event one of those that tries to encapsulate all four of those events?

**Comment by skrusty** [comment]
Not sure, but looking at the code, you can see (for example) BridgeDestroy fires it's own event!

https://github.com/skrusty/AsterNET/search?utf8=%E2%9C%93&q=BridgeDestroy

So hook into the AMI V2 events, not AMI V1.

This is a grey area in AsterNET right now, and something I am unsure how to handle moving forwards. Do we version off AsterNET (version 2.x.x) that only supports AMI v2? Suggestions and thoughts welcome.

**Comment by jonastelzio** [comment]
Right! Looking at the history it was actually me who implemented those events.

My opinion is that so long as there is no naming conflicts between the v1->2 events, we should just support them all.

@xiron3 just subscribe to the individual BridgeCreate/Destroy etc. The Bridge event is for older versions of Asterisk.

**Comment by skrusty** [comment]
@jonastelzio Might be worth adding something to the code comments (passed to intenseness) to reference that fact? Would be great of you could use Interfaces to mask over events for a specific AMI version.

E.g. 
```c#
var manager = (IAmiVersion1) new ConnectionManager(...);
```

But from what I remember with ARI, that's not really possible.

**Comment by xiron3** [comment]
ok, but i don't have BridgeCreate/Destroy events under ManagerConnection. Where can i find them ?
As I said, I downloaded latest AsterNet from Nuget.

**Comment by skrusty** [comment]
@xiron3 we can see they are not yet included in any release (https://github.com/skrusty/AsterNET/compare/v1.0.1...master)

You would need to download the source and compile yourself. We should get a new release out soon, but currently I am the only one who does it, and have to find time :]

**Comment by xiron3** [comment]
thanks for reply !
