### ISSUE TITLE
AsterNet ManagerConnection

### ISSUE THREAD

**Issue by MKMatthew** [skrusty/AsterNET#59]
I can succesfully establish connection with Astersik by using ManagerConnection but in the Asterisk server I can view the peers list by using **sip show peers** CLI command as 
Name/username             Host                                    Dyn Forcerport Comedia    ACL Port     Status      Description
1006                      (Unspecified)                            D  Yes        Yes         A  0        UNKNOWN
1007                      (Unspecified)                            D  Yes        Yes         A  0        UNKNOWN
2 sip peers [Monitored: 0 online, 2 offline Unmonitored: 0 online, 0 offline]

Why the Host name is still Showing as **unspecified**?

**Comment by skrusty** [comment]
Sounds more like a question for the Asterisk forums then AsterNET, this issue tracker is for issues specific to AsterNET, and by the sounds of it, the question you're asking relates to informaiton being output by Asterisk. Correct?

If so, please see: http://forums.asterisk.org/

**Comment by MKMatthew** [comment]
I hopefully expecting it is not a problem of AsterNet.
