### ISSUE TITLE
Unimplemented events

### ISSUE THREAD

**Issue by jonastelzio** [skrusty/AsterNET#7]
Hey!

I'm connecting to Asterisk 13.2 with AMI, and events like BridgeEnter, BridgeCreate, BridgeLeave, BridgeDestroy, AttendedTransfer and BlindTransfer doesn't appear to be implemented.

I'm down for implementing these myself and doing a pull-request. However I'm wondering if these are actually supposed to be handled by the Transfer and Bridge events? They they are, these Event Handlers doesn't fire - instead the events gets shown as Unknown Events in the UnhandledEvent-handler.

**Comment by skrusty** [comment]
Yeah, the existing events are to handle bridge events in earlier version of Asterisk.

If you'd like to implement the new events, then that would be very helpful! I look forwards to seeing your contributions.

**Comment by jonastelzio** [comment]
I already got them implemented and they're ready to be pull requested! :D

Just a quick question though: You don't have a .gitignore in your repository - any particular reason for that? I'm asking because I added one, and it made it into the commit I was planning on pull requesting.

**Comment by skrusty** [comment]
That's fine. No, there's no reason. The repo was migrated from codeplex, and I'd not noticed to be honest! Still new to github :)

**Comment by jonastelzio** [comment]
I'm sitting on this pull request now, thinking that stuff like TransfererPriority - that could actually be a string couldn't it? A priority doesn't have to be a number or am I mistaken?

**Comment by skrusty** [comment]
Priority should be a string!

**Comment by skrusty** [comment]
pull request #10 fixes this
